site:
  title: Global Nodes
  start_page: ROOT::index.adoc
  keys:
    language: en
content:
  sources:
    - url: .
      start_path: ./en/home
      branches: HEAD
    - url: .
      start_path: ./en/2021
      branches: HEAD
    - url: .
      start_path: ./en/gnt
      branches: HEAD
    - url: .
      start_path: ./en/gnm
      branches: HEAD
    - url: .
      start_path: ./en/prep
      branches: HEAD   
    - url: .
      start_path: ./en/buddies
      branches: HEAD
      start_path: ./en/gn2025
      branches: HEAD                         
    #- url: https://github.com/gbif/course-data-use.git
    #  start_path: en
    #  branches: antora
output:
  clean: false
  dir: ./output/en
runtime:
  fetch: false
  cache_dir: ./cache
ui:
  bundle:
    url: https://builds.gbif.org/job/tech-docs-theme/lastSuccessfulBuild/artifact/build/ui-bundle.zip
    #url: ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental_ui
asciidoc:
  attributes:
    idprefix: ''
    idseparator: '-'
    page-pagination: yes
    page-toctitle: 'Page contents'
    language: en
    null: ‚êÄ
#antora:
#  extensions:
#  - require: '@antora/lunr-extension'
#    index_latest_only: true
#    languages: [en]
